### PR TITLE
fix(docker): Pre-install Playwright Chromium browsers for automated t…

### LINKED ISSUE #725: [Bug]: Docker: Playwright verification fails - browsers not installed
### Operating System

Linux (Docker)

### Run Mode

Docker

### App Version

0.13.0

### Bug Description

AI agents running in automated testing mode fail when attempting Playwright verification because Playwright browsers are not installed in the Docker container. The default prompts instruct agents to verify implementations using Playwright, but Docker users have no browsers available.

### Root Cause Analysis

1. **Dockerfile** (`Dockerfile:70-79`) installs Playwright *system dependencies* (libglib2.0, libnss3, etc.) but NOT the browser binaries themselves

2. **Default prompts** (`libs/prompts/src/defaults.ts:840`) include `DEFAULT_PLAYWRIGHT_VERIFICATION_INSTRUCTIONS` that tell agents:
   > "After implementing the feature, you MUST verify it works correctly using Playwright"

3. **docker-compose.override.yml.example** shows a commented-out `playwright-cache` volume but:
   - No instructions on how to install browsers
   - Not mentioned in README or Docker documentation
   - Easy to miss for new users

4. **npm/Electron users don't hit this** because they typically have Playwright browsers in `~/.cache/ms-playwright` from local development

### Steps to Reproduce

1. Run Automaker with `docker compose up`
2. Create a feature and move it to "In Progress" (automated mode)
3. Wait for the AI agent to attempt Playwright verification
4. Agent fails with "Playwright browser installation was blocked by permissions"

### Expected Behavior

One of:
- Docker image should include Playwright browsers pre-installed
- Documentation should clearly explain how to set up Playwright for Docker users
- Playwright verification should be gracefully skipped/disabled when browsers unavailable

### Actual Behavior

AI agents fail verification step. Error message: "Playwright browser installation was blocked by permissions, but build verification confirms the implementation is working"

### Suggested Fix

**Option A: Pre-install browsers in Docker image (increases image size ~300MB)**
```dockerfile
# In Dockerfile, after installing system deps
RUN npx playwright install chromium
```

**Option B: Document the setup for Docker users**

Update README Docker section and docker-compose.override.yml.example:
```yaml
# docker-compose.override.yml
services:
  server:
    volumes:
      - playwright-cache:/home/automaker/.cache/ms-playwright

volumes:
  playwright-cache:
    name: automaker-playwright-cache
```

Then instruct users to run once:
```bash
docker exec automaker-server npx playwright install chromium
```

**Option C: Detect missing browsers and skip Playwright verification**

Add a check in the prompts or agent logic to gracefully skip Playwright verification when browsers aren't available, falling back to build-only verification.

### Screenshots

_N/A_

### Relevant Logs

```
Playwright browser installation was blocked by permissions, but build verification confirms the implementation is working
```

### Additional Context

The `docker-compose.override.yml.example` file (line 24-26) has the volume mount commented out with minimal context:
```yaml
# Playwright browser cache - persists installed browsers across container restarts
# Run 'npx playwright install --with-deps chromium' once, and it will persist
# - playwright-cache:/home/automaker/.cache/ms-playwright
```

This is easy to miss and doesn't explain that it's required for automated testing mode to work.

### Checklist

- [x] I have searched existing issues to ensure this bug hasn't been reported already
- [x] I have provided all required information above

### PR DESCRIPTION
**Pull request by Shironex**
Fixes #725

AI agents in automated testing mode require Playwright to verify implementations, but Docker containers had only system dependencies installed, not browser binaries. This caused verification failures with permissions errors.

Changes:
- Install Playwright Chromium in Dockerfile (~300MB increase)
- Update docker-compose.override.yml.example with clearer Playwright documentation
- Add "Playwright for Automated Testing" section to README
- Document optional volume mount for persisting browsers across rebuilds

Browsers are now pre-installed and work out of the box for Docker users.

## Summary by CodeRabbit

* **New Features**
  * Playwright Chromium pre-installed in the container for immediate E2E testing.
  * New "Adaptive" thinking level and adaptive-model behavior exposed in the UI and defaults.
  * New Codex model (GPT‑5.3‑Codex) and updated model defaults; authentication now reports auth type (oauth, api_key, cli).

* **Documentation**
  * README and docs updated with Playwright E2E guidance, persistence tips, docker-compose snippet, and troubleshooting.

* **Tests**
  * Unit tests added/updated to cover adaptive thinking and credential detection.

* **Chores**
  * .gitignore extended to ignore additional local data files.

### CODE REVIEW

**Comment by JasonBroderick** [comment]
## Tested this PR - found an issue and submitted a fix

I tested this PR on WSL2 Ubuntu and found that the Playwright install step fails during Docker build:

```
#63 [server server 16/20] RUN ./node_modules/.bin/playwright install chromium
#63 0.248 /bin/sh: 1: ./node_modules/.bin/playwright: not found
```

**Root cause:** The `server-builder` stage only copies `apps/server/package.json`, so playwright (which is only in `apps/ui/package.json` devDependencies) isn't available in the server's `node_modules`.

**Fix:** I've submitted #751 which adds `@playwright/test` to the server's devDependencies. After this fix, the build works correctly and Playwright verification runs successfully in Automaker.

Feel free to:
- Merge #751 separately, or
- Cherry-pick the commit into this branch, or  
- Implement the fix differently if you prefer

Happy to help however is most useful!

File: .gitignore [hunk 1]
```diff
@@ -95,3 +95,5 @@ data/.api-key
 data/credentials.json
 data/
 .codex/
+.mcp.json
+.planning
```
Comment (Shironex) [inline .gitignore]: > [!NOTE]
> **Nit - Style:** Missing trailing newline in .gitignore

The .gitignore file now lacks a trailing newline. POSIX standard defines a line as ending with a newline character. Many tools warn about this, and git itself flags it in the diff. This was likely introduced when the `.planning` entry was added.

**Problematic code:**
```text
+.planning\ No newline at end of file
```

**Suggested fix:**
```diff
Add a trailing newline after the last line:
```
.mcp.json
.planning
```
```

File: Dockerfile [hunk 2]
```diff
@@ -147,6 +148,15 @@ COPY --from=server-builder /app/apps/server/package*.json ./apps/server/
 # Copy node_modules (includes symlinks to libs)
 COPY --from=server-builder /app/node_modules ./node_modules
 
+# Install Playwright Chromium browser for AI agent verification tests
+# This adds ~300MB to the image but enables automated testing mode out of the box
+# Using the locally installed playwright ensures we use the pinned version from package-lock.json
+USER automaker
+RUN ./node_modules/.bin/playwright install chromium && \
```
Comment (Shironex) [inline Dockerfile:155]: > [!IMPORTANT]
> **Minor - Logic:** Misleading error handling in Playwright install RUN command

The `|| echo` at the end is connected to the `ls` command due to operator precedence, not to the entire chain. If `playwright install chromium` fails, the build will fail (which is correct). However, if `ls` fails (unlikely but possible), the `echo` silently masks the error. This creates a misleading success message. More importantly, the `||` structure makes the overall RUN step always succeed even if `ls` fails, which could hide a misconfigured browser install path.

**Problematic code:**
```text
RUN ./node_modules/.bin/playwright install chromium && \
    echo "=== Playwright Chromium installed ===" && \
    ls -la /home/automaker/.cache/ms-playwright/ || echo "Playwright browsers installed"
```

**Suggested fix:**
```diff
Use explicit grouping or just remove the fallback since the ls output is informational:
```dockerfile
RUN ./node_modules/.bin/playwright install chromium && \
    echo "=== Playwright Chromium installed ===" && \
    ls -la /home/automaker/.cache/ms-playwright/
```
```

File: apps/server/src/index.ts [hunk 3]
```diff
@@ -158,6 +194,27 @@ const BOX_CONTENT_WIDTH = 67;
...
+    pathsChecked.push(`Projects dir: ${cliAuthIndicators.checks.projectsDir.path}`);
+    for (const credFile of cliAuthIndicators.checks.credentialFiles) {
+      pathsChecked.push(`Credentials: ${credFile.path}`);
+    }
+
+    if (pathsChecked.length > 0) {
+      pathsCheckedInfo = `
+║                                                                     ║
+║  ${'Paths checked:'.padEnd(BOX_CONTENT_WIDTH)}║
+${pathsChecked.map((p) => `║    ${p.substring(0, BOX_CONTENT_WIDTH - 4).padEnd(BOX_CONTENT_WIDTH - 4)}  ║`).join('\n')}`;
```
Comment (Shironex) [inline apps/server/src/index.ts]: > [!IMPORTANT]
> **Minor - Logic:** Long paths silently truncated from the right in warning box

File paths in credential checks (e.g., `/home/user/.claude/.credentials.json`) can be quite long, especially in Docker or CI environments. The `substring(0, BOX_CONTENT_WIDTH - 4)` = `substring(0, 63)` will silently truncate longer paths. A label like `Credentials: /home/very-long-username/.claude/.credentials.json` (54+ chars) with the prefix would lose the end of the path. While the box formatting requires truncation, it would be more useful to truncate from the beginning (showing the filename) rather than the end.

**Problematic code:**
```typescript
pathsChecked.map((p) => `║    ${p.substring(0, BOX_CONTENT_WIDTH - 4).padEnd(BOX_CONTENT_WIDTH - 4)}  ║`).join('\n')
```

**Suggested fix:**
```diff
Consider showing the end of the path rather than the beginning when it's too long:
```typescript
const maxLen = BOX_CONTENT_WIDTH - 4;
const display = p.length > maxLen ? '...' + p.substring(p.length - maxLen + 3) : p;
pathsChecked.map((p) => {
  const display = p.length > maxLen ? '...' + p.slice(-(maxLen - 3)) : p;
  return `║    ${display.padEnd(maxLen)}  ║`;
}).join('\n')
```
```

File: apps/ui/src/components/views/board-view/shared/thinking-level-selector.tsx [hunk 4]
```diff
@@ -2,27 +2,33 @@ import { Label } from '@/components/ui/label';
...
+  model?: string;
 }
 
 export function ThinkingLevelSelector({
   selectedLevel,
   onLevelSelect,
   testIdPrefix = 'thinking-level',
+  model,
 }: ThinkingLevelSelectorProps) {
+  const levels = getThinkingLevelsForModel(model || '');
```
Comment (Shironex) [inline apps/ui/src/components/views/board-view/shared/thinking-level-selector.tsx:23]: > [!IMPORTANT]
> **Minor - Logic:** ThinkingLevelSelector defaults to non-adaptive levels when model is omitted

When `model` is not provided (undefined), the fallback is an empty string. `getThinkingLevelsForModel('')` returns the full manual thinking levels (none, low, medium, high, ultrathink) which excludes 'adaptive'. However, the `ThinkingLevelSelector` component is currently not imported anywhere in the codebase, so this is a latent issue. When it eventually gets used, callers must remember to pass the `model` prop for adaptive thinking to work correctly with Opus 4.6.

**Problematic code:**
```tsx
const levels = getThinkingLevelsForModel(model || '');
```

**Suggested fix:**
```diff
This is acceptable as-is since the component isn't yet used, but consider documenting the required model prop more prominently:
```tsx
/** Model ID is required for correct thinking level filtering.
 *  Without it, adaptive thinking won't be available for Opus 4.6. */
model?: string;
```
```

File: apps/server/src/routes/setup/routes/verify-claude-auth.ts [hunk 5]
```diff
@@ -320,9 +321,27 @@ export function createVerifyClaudeAuthHandler() {
...
 
+      // Determine specific auth type for success messages
+      let authType: 'oauth' | 'api_key' | 'cli' | undefined;
+      if (authenticated) {
+        if (authMethod === 'api_key') {
+          authType = 'api_key';
+        } else if (authMethod === 'cli') {
+          // Check if CLI auth is via OAuth (Claude Code subscription) or generic CLI
+          try {
+            const indicators = await getClaudeAuthIndicators();
```
Comment (Shironex) [inline apps/server/src/routes/setup/routes/verify-claude-auth.ts:333]: > [!NOTE]
> **Nit - Performance:** Redundant filesystem checks after successful auth verification

After successfully verifying authentication via a full SDK query (which already proved auth works), this code calls `getClaudeAuthIndicators()` again just to determine the auth type. This performs additional filesystem reads (checking settings files, stats cache, projects dir, credential files) on every successful CLI auth verification. While not a significant performance issue, the indicator data was already fetched during the startup check. Consider caching or reusing that data.

**Problematic code:**
```typescript
const indicators = await getClaudeAuthIndicators();
```

**Suggested fix:**
```diff
This is acceptable for now since it only runs during setup verification (not a hot path). Could be improved by caching the indicators or passing them through context, but low priority.
```

File: apps/server/src/index.ts [hunk 6]
```diff
@@ -121,21 +121,57 @@ const BOX_CONTENT_WIDTH = 67;
 // The Claude Agent SDK can use either ANTHROPIC_API_KEY or Claude Code CLI authentication
 (async () => {
   const hasAnthropicKey = !!process.env.ANTHROPIC_API_KEY;
+  const hasEnvOAuthToken = !!process.env.CLAUDE_CODE_OAUTH_TOKEN;
+
+  logger.debug('[CREDENTIAL_CHECK] Starting credential detection...');
```
Comment (Shironex) [inline apps/server/src/index.ts:126]: > [!NOTE]
> **Nit - Style:** Verbose debug logging with inconsistent prefix style

The new debug logging in the credential check is verbose - there are 6 debug log calls added throughout the auth detection flow. While helpful for debugging, the `[CREDENTIAL_CHECK]` prefix is inconsistent with other logging patterns in the file (which don't use bracketed prefixes). This is a minor style concern.

**Problematic code:**
```typescript
logger.debug('[CREDENTIAL_CHECK] Starting credential detection...');
logger.debug('[CREDENTIAL_CHECK] Environment variables:', {
  hasAnthropicKey,
  hasEnvOAuthToken,
});
```

**Suggested fix:**
```diff
Consider using a consistent prefix format, e.g., using the logger's category instead:
```typescript
const credLogger = createLogger('CredentialCheck');
credLogger.debug('Starting credential detection...');
```
Or keep it as-is since it's debug-level only and useful for troubleshooting.
```
